input {
  file {
    path => "/data/gold/anime_gold.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  csv {
    separator => ","
    columns => [
      "MAL_ID", "Name", "Score", "weighted_score", "Genres", "genres_list",
      "Type", "Episodes", "Status", "Studios", "studios_list", "studio_category",
      "Members", "Favorites", "Scored By", "Rank", "Popularity",
      "Watching", "Completed", "Dropped", "completion_rate", "drop_rate", "synopsis"
    ]
    skip_header => true
  }

  mutate {
    convert => {
      "MAL_ID"         => "integer"
      "Score"          => "float"
      "weighted_score" => "float"
      "Episodes"       => "integer"
      "Members"        => "integer"
      "Favorites"      => "integer"
      "Rank"           => "integer"
      "Popularity"     => "integer"
      "completion_rate" => "float"
      "drop_rate"      => "float"
    }
    remove_field => ["@version", "host", "path", "message"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "anime-%{+YYYY.MM}"
    document_id => "%{MAL_ID}"
  }
  stdout { codec => dots }
}
