apiVersion: 1

datasources:
  - name: AniDex-Scraper
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: anidex-animes
    jsonData:
      esVersion: "8.0.0"
      timeField: "@timestamp"
      maxConcurrentShardRequests: 5
    isDefault: false
