apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: anime-gold
    jsonData:
      esVersion: "8.0.0"
      timeField: "@timestamp"
      maxConcurrentShardRequests: 5
    isDefault: true
